"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { LatencyCard } from "@/components/status/latency-card";
import { PredictionCard } from "@/components/status/prediction-card";
import { RuntimeHealthCard } from "@/components/status/runtime-health-card";
import { useRuntimeStatus } from "@/components/runtime/run-status-provider";
import { ErrorState, PageHeader, SectionCard, StatusBadge } from "@/components/ui/design-system";
import { consoleApi } from "@/lib/api/client";
import { connectRun } from "@/lib/websocket/run-stream";
import type { DatasetSummary, ModelSummary, PredictionPayload, RunState } from "@/types/api";

const activeStates: RunState[] = ["starting", "running", "stopping"];

export default function ReplayPage() {
  const { registerActiveRun, latency, runtimeHealth, inputContract, fatalReason } = useRuntimeStatus();
  const [datasets, setDatasets] = useState<DatasetSummary[]>([]); const [models, setModels] = useState<ModelSummary[]>([]);
  const [datasetKey, setDatasetKey] = useState(""); const [session, setSession] = useState(""); const [modelId, setModelId] = useState("");
  const [runId, setRunId] = useState(""); const [state, setState] = useState<RunState>("idle"); const [prediction, setPrediction] = useState<PredictionPayload | null>(null); const [error, setError] = useState("");
  const socket = useRef<WebSocket | null>(null);
  useEffect(() => { Promise.all([consoleApi.datasets(), consoleApi.models()]).then(([nextDatasets, nextModels]) => { setDatasets(nextDatasets); setModels(nextModels.filter(model => model.runtime_verified)); const dataset = nextDatasets[0]; setDatasetKey(dataset ? `${dataset.id}|${dataset.subject_id}` : ""); setSession(dataset?.sessions[0] ?? ""); setModelId(nextModels.find(model => model.runtime_verified)?.id ?? ""); }).catch(value => setError(value instanceof Error ? value.message : "无法读取回放配置")); return () => socket.current?.close(); }, []);
  const selectedDataset = useMemo(() => datasets.find(item => `${item.id}|${item.subject_id}` === datasetKey), [datasets, datasetKey]);
  const selectedModel = models.find(item => item.id === modelId); const running = activeStates.includes(state);
  function subscribe(id: string) { socket.current?.close(); socket.current = connectRun(id, event => { if (event.type === "state") setState(event.payload.state as RunState); if (event.type === "prediction") setPrediction(event.payload as unknown as PredictionPayload); if (event.type === "error" && event.payload.fatal === true) setPrediction(null); }); }
  async function start() { if (!selectedDataset || !selectedModel || !session) return; setError(""); setPrediction(null); try { const created = await consoleApi.startReplay({ dataset_id: selectedDataset.id, subject_id: selectedDataset.subject_id, session, model_id: selectedModel.id, compute_device: "cpu", replay_speed: 1, max_windows: 100, confidence_threshold: 0.55 }); setRunId(created.run_id); setState("starting"); registerActiveRun(created.run_id); subscribe(created.run_id); } catch (value) { setError(value instanceof Error ? value.message : "无法启动回放"); } }
  async function stop() { if (runId) await consoleApi.stopRun(runId).catch(value => setError(value instanceof Error ? value.message : "无法停止回放")); }
  async function restart() { if (runId) { setPrediction(null); await consoleApi.restartRun(runId).then(() => { setState("starting"); registerActiveRun(runId); }).catch(value => setError(value instanceof Error ? value.message : "无法重新开始回放")); } }
  return <><PageHeader title="离线回放" description="使用 Runtime Package 和真实数据集执行可控伪实时推理。" action={runId ? <span className="compute-chip">{runId}</span> : undefined} />{(error || fatalReason) && <ErrorState message={fatalReason ?? error} />}<div className="dashboard-grid"><SectionCard title="回放配置" className="span-8"><div className="field-grid"><div className="field"><label>数据集 / 被试</label><select value={datasetKey} disabled={running} onChange={event => { setDatasetKey(event.target.value); const item = datasets.find(dataset => `${dataset.id}|${dataset.subject_id}` === event.target.value); setSession(item?.sessions[0] ?? ""); }}><option value="">请选择</option>{datasets.map(item => <option key={`${item.id}-${item.subject_id}`} value={`${item.id}|${item.subject_id}`}>{item.name} · {item.subject_id}</option>)}</select></div><div className="field"><label>Session</label><select value={session} disabled={running} onChange={event => setSession(event.target.value)}>{selectedDataset?.sessions.map(value => <option key={value}>{value}</option>)}</select></div><div className="field"><label>模型</label><select value={modelId} disabled={running} onChange={event => setModelId(event.target.value)}>{models.map(model => <option key={model.id} value={model.id}>{model.model_name} · {model.window_sec}s</option>)}</select></div></div></SectionCard><SectionCard title="运行控制" className="span-4"><div className="control-stack"><StatusBadge tone={state === "running" ? "running" : state === "failed" ? "danger" : "idle"}>{state}</StatusBadge><button className="button button-primary" disabled={running} onClick={start}>开始</button><button className="button button-danger" disabled={!running} onClick={stop}>停止</button><button className="button button-secondary" disabled={!runId || running} onClick={restart}>重新开始</button></div></SectionCard><div className="span-5"><PredictionCard prediction={prediction?.predicted_name} confidence={prediction?.confidence} probabilities={prediction?.probabilities} command={fatalReason || inputContract?.safe === false ? "STOP" : prediction?.command} invalid={Boolean(fatalReason || inputContract?.safe === false)} /></div><div className="span-3"><LatencyCard value={latency} /></div><div className="span-4"><RuntimeHealthCard value={runtimeHealth} /></div></div></>;
}
